// ISO codes also support feeds that return a code instead of a country name.
const flagCountries: Record<string, string[]> = {
  us: ["United States", "United States of America", "USA"],
  gb: ["United Kingdom", "UK", "Great Britain"],
  eu: ["Euro Area", "Eurozone", "Euro Zone", "European Union", "EMU"],
  jp: ["Japan"],
  ca: ["Canada"],
  au: ["Australia"],
  nz: ["New Zealand"],
  ch: ["Switzerland"],
  cn: ["China"],
  de: ["Germany"],
  fr: ["France"],
  it: ["Italy"],
  es: ["Spain"],
  kh: ["Cambodia"],
  no: ["Norway"],
  se: ["Sweden"],
  dk: ["Denmark"],
  fi: ["Finland"],
  nl: ["Netherlands", "Netherlands, The", "The Netherlands"],
  be: ["Belgium"],
  at: ["Austria"],
  pt: ["Portugal"],
  gr: ["Greece"],
  ie: ["Ireland"],
  is: ["Iceland"],
  pl: ["Poland"],
  cz: ["Czech Republic", "Czechia"],
  hu: ["Hungary"],
  ro: ["Romania"],
  bg: ["Bulgaria"],
  hr: ["Croatia"],
  sk: ["Slovakia"],
  si: ["Slovenia"],
  ee: ["Estonia"],
  lv: ["Latvia"],
  lt: ["Lithuania"],
  cy: ["Cyprus"],
  mt: ["Malta"],
  lu: ["Luxembourg"],
  kr: ["South Korea", "Korea", "Republic of Korea"],
  in: ["India"],
  br: ["Brazil"],
  mx: ["Mexico"],
  ru: ["Russia", "Russian Federation"],
  za: ["South Africa"],
  tr: ["Turkey", "Türkiye"],
  id: ["Indonesia"],
  sg: ["Singapore"],
  hk: ["Hong Kong"],
  th: ["Thailand"],
  my: ["Malaysia"],
  ph: ["Philippines"],
  vn: ["Vietnam", "Viet Nam"],
  tw: ["Taiwan"],
  ar: ["Argentina"],
  cl: ["Chile"],
  co: ["Colombia"],
  pe: ["Peru"],
  il: ["Israel"],
  sa: ["Saudi Arabia"],
  ae: ["United Arab Emirates", "UAE"],
  kw: ["Kuwait"],
  eg: ["Egypt"],
  ng: ["Nigeria"],
  pk: ["Pakistan"],
  ua: ["Ukraine"],
};

const countryCodes = new Map(
  Object.entries(flagCountries).flatMap(([code, names]) =>
    [code, ...names].map((name) => [name.toLowerCase(), code] as const),
  ),
);

export function countryFlagCode(country: string): string | null {
  return countryCodes.get(country.trim().toLowerCase()) ?? null;
}
