export const countries: Record<string, { km: string; flag: string; currency: string }> = {
  'United States': { km: 'សហរដ្ឋអាមេរិក', flag: '🇺🇸', currency: 'USD' },
  'United Kingdom': { km: 'ចក្រភពអង់គ្លេស', flag: '🇬🇧', currency: 'GBP' },
  'Euro Area': { km: 'តំបន់ចាយប្រាក់អឺរ៉ូ', flag: '🇪🇺', currency: 'EUR' },
  Japan: { km: 'ជប៉ុន', flag: '🇯🇵', currency: 'JPY' },
  Canada: { km: 'កាណាដា', flag: '🇨🇦', currency: 'CAD' },
  Australia: { km: 'អូស្ត្រាលី', flag: '🇦🇺', currency: 'AUD' },
  'New Zealand': { km: 'នូវែលសេឡង់', flag: '🇳🇿', currency: 'NZD' },
  Switzerland: { km: 'ស្វីស', flag: '🇨🇭', currency: 'CHF' },
  China: { km: 'ចិន', flag: '🇨🇳', currency: 'CNY' },
  Germany: { km: 'អាល្លឺម៉ង់', flag: '🇩🇪', currency: 'EUR' },
  France: { km: 'បារាំង', flag: '🇫🇷', currency: 'EUR' },
  Italy: { km: 'អ៊ីតាលី', flag: '🇮🇹', currency: 'EUR' },
  Spain: { km: 'អេស្ប៉ាញ', flag: '🇪🇸', currency: 'EUR' },
  Cambodia: { km: 'កម្ពុជា', flag: '🇰🇭', currency: 'KHR' },
};
